services:
  - type: web
    name: gesture-controll
    runtime: python
    pythonVersion: 3.9
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
